### ISSUE TITLE
[NETE2ESDK][RHEL] After uninstalling .NET SDK in terminal, an error occurred while installing .NET SDK for the first time in vscode.

### ISSUE THREAD

**Issue by YingyingYuan9** [dotnet/vscode-dotnet-runtime#2184]
### Describe the bug.

After uninstalling .NET SDK in terminal, an error occurred while installing .NET SDK for the first time in vscode.

### Please attach log file(s) here if you have any.

[log.zip](https://github.com/user-attachments/files/19334827/log.zip)

### Reproduction Steps

1. On RHEL 9.5, run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension).
2. Use the version it provided, which is 7.0.103. Hit enter.
3. In the terminal, run the command 'sudo dnf remove dotnet-sdk-[correspond version]' to uninstall sdk.
4. In the terminal, run the command 'rpm -qa | grep dotnet' to make sure it's uninstalled.
5. Open vscode, run the sample command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension).
6. Enter a version like 6.0.1xx to install .NET SDK
7. Observe the installation

### Expected Behavior

The .NET SDK should be installed successfully.

### Exceptions & Errors (if any)

An error message appears, but the sdk was installed successfully

![Image](https://github.com/user-attachments/assets/288a58f0-e9fb-49e8-bb56-07030e821b0d)

![Image](https://github.com/user-attachments/assets/337e467e-c869-49db-a58e-c9e3afa9312e)

![Image](https://github.com/user-attachments/assets/6cbef7bd-e5dc-4e63-9728-f0842670ed39)

**Note**
The .NET SDK can be installed successfully if try to install the SDK again

![Image](https://github.com/user-attachments/assets/eadf86e0-88a7-40e3-95fc-808a8bb6764e)

### .NET Install Tool Version

v 2.2.9-c

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.98.2

**Comment by nagilson** [comment]
Ah.... yes this is a bug because /usr/lib64/dotnet/dotnet is not a folder so the Validation check failed. Probably need to fix but don't need to respin vendor testing all over for this as its straight foward and doesnt impact other code.

**Comment by YingyingYuan9** [comment]
Also repro on today‘s new build 2.2.9 on ubuntu24.04
If use the command ‘Install .NET SDK Globally via .NET Install Tool (Former Runtime Extension)’, after the first installation fails, the installation again prompts that .NET SDK already exists; 

![Image](https://github.com/user-attachments/assets/acc2c47f-e2bc-4f82-80d4-714ae01c6013)

If use the command ‘.NET Install Tool - Install the .NET SDK System-Wide’, after the first installation fails, the installation again succeeds.

![Image](https://github.com/user-attachments/assets/72569092-779f-4f76-b846-e2fb07e4d9bd)

**Comment by nagilson** [comment]
I believe this is fixed now. It seems the issue was the existing install code calling false for fail on Err which caused the later one to fail for real when it thought it didnt need to install again

**Comment by YingyingYuan9** [comment]
This issue is still reproduced with the new build v2.3.0

![Image](https://github.com/user-attachments/assets/5fe1e9d5-d768-4756-a10a-a608c3f11c0b)

**Comment by YingyingYuan9** [comment]
Still reproduced with the new build v2.3.1

![Image](https://github.com/user-attachments/assets/720bceae-51a7-41f9-b9c8-883f1f02adac)

**Comment by YingyingYuan9** [comment]
Fixed on the new build on Ubuntu24.04.
![Image](https://github.com/user-attachments/assets/b446f979-aae7-434a-907e-aecb70947287)

**Comment by YingyingYuan9** [comment]
Fixed on the new build v2.3.3 on RHEL 9.5.

![Image](https://github.com/user-attachments/assets/7ec76113-851e-4004-aa61-d4781dc5b2bd)
